### PR TITLE
Exclude more files and folders

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by simonschaufi** [comment]
if you don't agree with the modifications, please just update the file yourself and remove the lines that you don't want.

**Comment by simonschaufi** [comment]
ok. I made a fulltext search for the stubs folder and didn't find it in the src folder. I didn't change the psalm.xml.dist file, it is just shown because of the eol.

**Comment by paras-malhotra** [comment]
Stubs are used here: https://github.com/enlightn/enlightn/blob/cab8eddffcfb20aa2fe720c662fe89e57f28e593/phpstan.neon#L19-L20

The phpstan.neon file is used here: https://github.com/enlightn/enlightn/blob/cab8eddffcfb20aa2fe720c662fe89e57f28e593/src/PHPStan.php#L96-L116

Hope this clarifies :)

**Comment by simonschaufi** [comment]
yes, thanx!

**Pull request closed without merging**
